library(ncdf4)

context("NCDF SG Base Fixture Tests")

# Data Prep - this could be included in tests, but then rgeos would be required for tests.
library(jsonlite)
library(rgeos)
fixtureData<-fromJSON(readLines(system.file('extdata','fixture_wkt.json', package = 'NCDFSG'),warn = FALSE))
multipointData <- readWKT(fixtureData[["2d"]]$multipoint)
pointData <- readWKT(fixtureData[["2d"]]$point)
lineData <- readWKT(fixtureData[["2d"]]$linestring)
multiLineData <- readWKT(fixtureData[["2d"]]$multilinestring)
polygonData <- readWKT(fixtureData[["2d"]]$polygon)
polygon_holeData <- readWKT(fixtureData[["2d"]]$polygon_hole)
multipolygonData <- readWKT(fixtureData[["2d"]]$multipolygon)
multipolygon_holeData <- readWKT(fixtureData[["2d"]]$multipolygon_hole)
multipolygons_holesData <- readWKT(fixtureData[["2d"]]$multipolygons_holes)
multigeometries_polygons_holesData <- readWKT(paste0("GEOMETRYCOLLECTION(",fixtureData[["2d"]]$multipolygons_holes,", ",fixtureData[["2d"]]$multipolygon_hole,")"), id = c("1","2"))
saveRDS(multipointData,file="data/multiPointData.rds")
saveRDS(pointData,file="data/pointData.rds")
saveRDS(lineData, file="data/lineData.rds")
saveRDS(multiLineData, file="data/multiLineData.rds")
saveRDS(polygonData, file="data/polygonData.rds")
saveRDS(polygon_holeData, file="data/polygon_holeData.rds")
saveRDS(multipolygonData, file="data/multipolygonData.rds")
saveRDS(multipolygon_holeData, file="data/multipolygon_holeData.rds")
saveRDS(multipolygons_holesData, file="data/multipolygons_holes.rds")
saveRDS(multigeometries_polygons_holesData, file="data/multigeometries_polygons_holes.rds")
