library(ncdf4)

context("NCDF SG point tests")

test_that("Point_timeSeries", {
  multipointData <- readRDS("data/pointData.rds")
  nc_file <- multiPoint_timeSeries(nc_file=tempfile(), multiPoint = multipointData)
  nc<-nc_open(nc_file)
  expect_equal(class(nc),"ncdf4")
  expect_equal(nc$dim$station$vals,c(1))
  expect_equal(as.numeric(ncvar_get(nc,'lat')),as.numeric(multipointData@coords[,2]))
  expect_equal(as.numeric(ncvar_get(nc,'lon')),as.numeric(multipointData@coords[,1]))
  expect_equivalent(ncatt_get(nc,varid=0,"Conventions")$value,"CF-1.7")
  expect_equivalent(ncatt_get(nc,varid="station_name","standard_name")$value,"station_id")
  expect_equivalent(ncatt_get(nc,varid="station_name","cf_role")$value,"timeseries_id")
  expect_equivalent(ncatt_get(nc,varid="lat","standard_name")$value,"latitude")
  expect_equivalent(ncatt_get(nc,varid="lon","standard_name")$value,"longitude")
})

test_that("multiPoint_timeSeries", {
  multipointData <- readRDS("data/multipointData.rds")
  nc_file <- multiPoint_timeSeries(nc_file=tempfile(), multiPoint = multipointData)
  nc<-nc_open(nc_file)
  expect_equal(class(nc),"ncdf4")
  expect_equal(nc$dim$station$vals,c(1,2,3,4))
  expect_equal(as.numeric(ncvar_get(nc,'lat')),as.numeric(multipointData@coords[,2]))
  expect_equal(as.numeric(ncvar_get(nc,'lon')),as.numeric(multipointData@coords[,1]))
  expect_equivalent(ncatt_get(nc,varid=0,"Conventions")$value,"CF-1.7")
  expect_equivalent(ncatt_get(nc,varid="station_name","standard_name")$value,"station_id")
  expect_equivalent(ncatt_get(nc,varid="station_name","cf_role")$value,"timeseries_id")
  expect_equivalent(ncatt_get(nc,varid="lat","standard_name")$value,"latitude")
  expect_equivalent(ncatt_get(nc,varid="lon","standard_name")$value,"longitude")
})
